
services:
  # üñ•Ô∏è Backend - Spring Boot
  backend:
    build:
      context: ./backend/flashfly

    container_name: flashfly
    ports:
      - "8080:8080"
    depends_on:
      - db-postgres   # üîÅ cambia aqu√≠ a "db-mysql" si quieres usar MySQL
    env_file:
      - .env
    environment:
      # Para PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-postgres:5432/flashfly
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

  # üóÑÔ∏è Base de datos PostgreSQL
  db-postgres:
    image: postgres:15
    container_name: flashfly-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flashfly
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

# üîÅ Vol√∫menes persistentes (opcional)
volumes:
  pgdata:
#  mysqldata:

