
services:
  # üñ•Ô∏è Backend - Spring Boot
  backend:
    build:
      context: ./backend/flashfly
    container_name: flashfly-back
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/flashfly?authSource=admin

  mongo:
    image: mongo:6
    container_name: flashfly-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodata:/data/db

  frontend:
    build:
      context: ./frontend/flashfly
    container_name: flashfly-front
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080

# üîÅ Vol√∫menes persistentes (opcional)
volumes:
  mongodata:


